app/routes/admin/main.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    session,
    current_app,
    jsonify,
)
from sqlalchemy import inspect
from app.models import db, AdminUser, Question, Answer
from app import bcrypt
import psutil
import os

admin_bp = Blueprint("admin", __name__)


def login_required(f):
    def wrap(*args, **kwargs):
        if "admin_user" not in session:
            return redirect(url_for("admin.admin_login"))
        return f(*args, **kwargs)

    return wrap


@admin_bp.route("/")
def admin_index():
    return redirect(url_for("admin.admin_login"))


@admin_bp.route("/login", methods=["GET", "POST"])
def admin_login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")

        admin_user = AdminUser.query.filter_by(username=username).first()

        if admin_user and bcrypt.check_password_hash(admin_user.password, password):
            session["admin_user"] = admin_user.id
            return redirect(url_for("admin.admin_dashboard"))

        flash("아이디 또는 비밀번호가 올바르지 않습니다.", "danger")
        return redirect(url_for("admin.admin_login"))
    elif request.method == "GET":
        if session.get("admin_user"):
            return redirect(url_for("admin.admin_dashboard"))
        else:
            return render_template("admin/login.jinja2", title="Login")


@admin_bp.route("/register", methods=["GET", "POST"])
def admin_register():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password_confirm")
        register_key = request.form.get("register_key")

        username_check = AdminUser.query.filter_by(username=username).first()

        if username_check:
            flash("이미 존재하는 아이디 입니다.", "danger")

        if register_key != current_app.config["REGISTER_KEY"]:
            flash("관리자 패스워드 키가 올바르지 않습니다.", "danger")
            return redirect(url_for("admin.admin_register"))

        admin_user = AdminUser(username, password)
        db.session.add(admin_user)
        db.session.commit()

        flash("관리자 등록이 완료되었습니다.", "success")
        return redirect(url_for("admin.admin_login"))

    return render_template("admin/register.jinja2", title="Register")


@admin_bp.route("/logout")
def admin_logout():
    session.pop("admin_user", None)
    flash("로그아웃 되었습니다.", "success")
    return redirect(url_for("admin.admin_login"))


def get_system_usage():
    cpu_usage = psutil.cpu_percent(interval=1)
    memory_info = psutil.virtual_memory()
    memory_usage = memory_info.percent
    disk_info = psutil.disk_usage("/")
    disk_usage = disk_info.percent
    network_info = psutil.net_io_counters()
    network_sent = round(network_info.bytes_sent / 1024**2, 1)
    network_recv = round(network_info.bytes_recv / 1024**2, 1)
    return cpu_usage, memory_usage, disk_usage, network_sent, network_recv


@login_required
@admin_bp.route("/dashboard", methods=["GET"])
def admin_dashboard():
    return render_template(
        "admin/dashboard.jinja2",
        title="Dashboard",
    )


@login_required
@admin_bp.route("/usage", methods=["GET"])
def usage():
    cpu_usage, memory_usage, disk_usage, network_sent, network_recv = get_system_usage()
    return jsonify(
        cpu=cpu_usage,
        memory=memory_usage,
        disk=disk_usage,
        network_sent=network_sent,
        network_recv=network_recv,
    )


@login_required
@admin_bp.route("/database", methods=["GET"])
def admin_database():
    inspector = inspect(db.engine)
    schema = {}
    for table_name in inspector.get_table_names():
        columns = inspector.get_columns(table_name)
        schema[table_name] = [
            {"name": column["name"], "type": column["type"]} for column in columns
        ]
    return render_template("admin/database.jinja2", title="Database", schema=schema)

app/templates/layout/base.jinja2
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - WISE IT Admin</title>
    {% else %}
    <title>WISE IT Admin</title>
    {% endif %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}">
    <link href="{{ url_for('static', filename='Bootstrap/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='Bootstrap/icon/bootstrap-icons.min.css') }}">
    <link href="{{ url_for('static', filename='CSS/init.css') }}" rel="stylesheet">
    {% block style %}{% endblock style %}
</head>

<body>
    {% include 'layout/navbar.jinja2' %}

    <div class="py-5">
        <div class="container py-5">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>
    </div>

    <script src="{{ url_for('static', filename='Bootstrap/bootstrap.bundle.min.js') }}"></script>
    {% block script %}{% endblock script %}
</body>

</html>

app/templates/layout/base_auth.jinja2
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - WISE IT Admin</title>
    {% else %}
    <title>WISE IT Admin</title>
    {% endif %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.png') }}">
    <link href="{{ url_for('static', filename='Bootstrap/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='Bootstrap/icon/bootstrap-icons.min.css') }}">
    <link href="{{ url_for('static', filename='CSS/init.css') }}" rel="stylesheet">
    {% block style %}{% endblock style %}
</head>

<body>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
        </div>

        {% block content %}{% endblock %}
    </div>

    <script src="{{ url_for('static', filename='Bootstrap/bootstrap.bundle.min.js') }}"></script>
    {% block script %}{% endblock script %}
</body>

</html>

app/templates/layout/navbar.jinja2
<nav class="navbar fixed-top navbar-expand-lg bg-light" data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('admin.admin_dashboard') }}">
            <img src="{{ url_for('static', filename='favicon.png') }}" alt="Logo" height="24" width="24"
                class="d-inline-block align-text-top" />
            WISE IT: Dashboard
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                {# <li class="nav-item">
                    <a class="nav-link {% if request.path == '/admin/dashboard' %}active{% endif %}"
                        href="{{ url_for('admin.admin_dashboard') }}">HOME
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li> #}
                <li class="nav-item dropdown">
                    <a class="nav-link {% if request.path.startswith('/admin/api_endpoint') %}active{% endif %} dropdown-toggle"
                        href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        API Endpoint
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('api_endpoint.api_endpoint_user') }}">User</a>
                        </li>
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item"
                                href="{{ url_for('api_endpoint.api_endpoint_article') }}">Article</a></li>
                        <li><a class="dropdown-item"
                                href="{{ url_for('api_endpoint.api_endpoint_qaboard') }}">QABoard</a></li>
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item"
                                href="{{ url_for('api_endpoint.api_endpoint_sqool_artist') }}">SQooL:
                                Artist</a></li>
                        <li><a class="dropdown-item"
                                href="{{ url_for('api_endpoint.api_endpoint_sqool_movie') }}">SQooL:
                                Movie</a>
                        </li>
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item {% if request.path == '/admin/api_endpoint/common' %}active{% endif %}"
                                href="{{ url_for('api_endpoint.api_endpoint_common') }}">Common</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path.startswith('/admin/api_test') %}active{% endif %}"
                        href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        API Testing
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('api_test.sql_query') }}">SQL Query</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{{ url_for('api_test.upload_image') }}">Image
                                Upload</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('api_test.upload_thumbnail') }}">Thumbnail
                                Upload</a></li>
                        <li><a class="dropdown-item " href="{{ url_for('api_test.upload_file') }}">File
                                Upload</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('api_test.delete_file') }}">Delete File</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path.startswith('/admin/sql_doc') %}active{% endif %}"
                        href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        SQL Document
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="nav-link" href="{{ url_for('sql_doc.admin_category_list') }}">Category</a></li>
                        <li><a class="nav-link" href="{{ url_for('sql_doc.admin_document_list') }}">Document</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path.startswith('/admin/community') %}active{% endif %}"
                        href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Community
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="nav-link" href="{{ url_for('article.admin_article_list') }}">Article</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="nav-link" href="{{ url_for('qa_board.admin_qaboard_list') }}">QABoard</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Database
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('admin.admin_database') }}">WISE IT: Database</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">SQooL: Artist Database</a></li>
                    </ul>
                </li>
            </ul>
            <div class="d-flex me-sm-2 gap-2">
                <a class="btn btn-success btn-sm" href="https://sqool.wiseit.kr" target="_blank">SQooL: Home</a>
                <a class="btn btn-danger btn-sm" href="{{ url_for('admin.admin_logout') }}">로그아웃</a>
            </div>
        </div>
    </div>
</nav>